apiVersion: batch/v1
kind: Job
metadata:
  name: job-asset-export-tradingnetworks-r-<TAG>
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false" 
    spec:
      securityContext:
        runAsUser: 1724
      restartPolicy: Never
      containers:
      - name: asset-export-tradingnetworks
        image: wm.msr.tn:10.15
        command: 
        - "sh"
        - "-c"
        - |
          mkdir -p /opt/softwareag/install/bin
          cp /tmp/* /scripts/
          cd /scripts
          chmod 755 export.sh
          ./export.sh
        volumeMounts:
          - mountPath: /scripts
            name: create-dir
          - mountPath: /tmp
            name: export-script
          - mountPath: /opt/softwareag/IntegrationServer/bin/../config/licenseKey.xml
            subPath: licenseKey.xml
            name: licensekey
          - name: application-properties
            mountPath: /opt/softwareag/IntegrationServer/application.properties
            subPath: application.properties   
          - name: setenv-cp  
            mountPath: /opt/softwareag/IntegrationServer/packages/WmTN/bin/setcp.sh
            subPath: setcp.sh        
          - name: setenv   
            mountPath: /opt/softwareag/install/bin/setenv.sh
            subPath: setenv.sh                                          
      volumes:
        - name: export-script
          configMap:
            name: tn-importexportscript-cm
        - name: create-dir
          emptyDir: {}
        - name: licensekey
          configMap:
            name: webmethodslicensekeys
        - name: application-properties
          configMap:
            name: tn-appprop-cm 
        - name: setenv-cp
          configMap:
            name: tn-utilfiles-cm    
        - name: setenv
          configMap:
            name: tn-utilfiles-cm                            