apiVersion: batch/v1
kind: Job
metadata:
  name: job-asset-export-tradingnetworks-r-<TAG>
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false" 
    spec:
      restartPolicy: Never
      containers:
      - name: asset-export-tradingnetworks
        securityContext:
          privileged: true      
        image: wm.msr.tn:10.15
        resources:
          limits:
            cpu: "1"
            memory: "2G" 
          requests:
            cpu: "0.25"
            memory: "1G"  
        env:
        - name: JAVA_MIN_MEM
          value: "1024M"
        - name: JAVA_MAX_MEM
          value: "2048M"            
        command: 
        - "sh"
        - "-c"
        - |
          mkdir -p /opt/softwareag/install/bin
          # Initiate the startup for MSR to effect the JDBC pools
          /opt/softwareag/IntegrationServer/bin/startup.sh

          # Wait for MSR to come up
          while [ $(curl -sw '%{http_code}' "http://localhost:5555/health/liveness" -o /dev/null) -ne 200 ]; do
            sleep 2;
            tail -20 /opt/softwareag/IntegrationServer/logs/server.log
          done     

          # When MSR is inactive, initiate the import process
          cd /opt/softwareag/IntegrationServer/packages/WmTN/bin    
          # Execute the TN export command to effect the new assets
          echo "Starting export--------------------"
          ./tnexport.sh -bin ExportedData<TAG> -zipdir /scripts -all
          echo "Completing export------------------"

          # When startup is complete, initiate the shutdown sequence
          /opt/softwareag/IntegrationServer/bin/shutdown.sh           
          cp /tmp/* /scripts/
          cd /scripts
          chmod 755 export.sh
        volumeMounts:
          - mountPath: /scripts
            name: scripts-dir     
          - mountPath: /tmp
            name: export-script
          - mountPath: /opt/softwareag/IntegrationServer/bin/../config/licenseKey.xml
            subPath: licenseKey.xml
            name: licensekey
          - name: application-properties
            mountPath: /opt/softwareag/IntegrationServer/application.properties
            subPath: application.properties   
          - name: setenv-cp  
            mountPath: /opt/softwareag/IntegrationServer/packages/WmTN/bin/setcp.sh
            subPath: setcp.sh        
          - name: setenv   
            mountPath: /opt/softwareag/install/bin/setenv.sh
            subPath: setenv.sh                                          
      volumes:
        - name: export-script
          configMap:
            name: tn-importexportscript-cm
        - name: scripts-dir
          emptyDir: {}        
        - name: licensekey
          configMap:
            name: webmethodslicensekeys
        - name: application-properties
          configMap:
            name: tn-appprop-cm 
        - name: setenv-cp
          configMap:
            name: tn-utilfiles-cm    
        - name: setenv
          configMap:
            name: tn-utilfiles-cm                            