apiVersion: v1
kind: ConfigMap
metadata:
  name: tn-importexportscript-cm
data:
  import.sh: |-
    #!/bin/bash
    # Initiate the startup for MSR to effect the JDBC pools
    /opt/softwareag/IntegrationServer/bin/startup.sh

    # Wait for MSR to come up
    while [ $(curl -sw '%{http_code}' "http://localhost:5555/health/liveness" -o /dev/null) -ne 200 ]; do
      sleep 2;
    done     

    # When startup is complete, initiate the shutdown sequence
    /opt/softwareag/IntegrationServer/bin/shutdown.sh 

    # When MSR is inactive, initiate the import process
    cd /opt/softwareag/IntegrationServer/packages/WmTN/bin    

    # Download from Repository
    curl -LJO "https://raw.githubusercontent.com/kplogesh/webmethods-tradingnetworks-devops/develop/applications/tradingnetworks/sourcecode/tn-assets/ExportedData.bin" > ExportedData.bin 
    
    # Execute the TN import command to effect the new assets
    ./tnimport.sh -file TNImport.xml
