pipeline {
    agent any 
    stages {
        stage('DEV - TN Export Task - K8S') 
        { 
            steps 
            {
                sh "chmod +x -R ${env.WORKSPACE}"
                withCredentials([file(credentialsId: 'vadigcs62496k8s', variable: 'KUBECONFIG')]) 
                {
                    sh 'pipeline/common.lib/export-task.sh ${BUILD_NUMBER} development'
                }
            }
        }               
        stage('Staging - TN Import Job - K8S') 
        { 
            steps 
            {
                sh 'unzip ExportedData-${BUILD_NUMBER}.zip'
                withCredentials([file(credentialsId: 'vadigcs62496k8s', variable: 'KUBECONFIG')]) 
                {
                    sh 'pipeline/common.lib/import-task.sh ${BUILD_NUMBER} staging staging'
                }
            }
        }
        stage('Build Application Image') 
        { 
            steps 
            {
                sh 'pipeline/common.lib/build.sh ${BUILD_NUMBER}'
            }
        }         
        stage('Staging - Deploy MSR - K8S') { 
            steps 
            {
                withCredentials([file(credentialsId: 'vadigcs62496k8s', variable: 'KUBECONFIG')]) 
                {
                    sh 'pipeline/common.lib/deploy.sh ${BUILD_NUMBER} staging staging'
                }
            }
        }    
    }
    post { 
        always { 
            cleanWs()
        }
    }      
}