apiVersion: v1
kind: Service
metadata:
  name: staging-tradingnetworks
  labels:
    app: staging-tradingnetworks
  annotations:
    prometheus.io/scrape: 'true'    
    prometheus.io/port: '5555'
spec:
  selector:
    app: staging-tradingnetworks
    component: msr
  ports:
    - port: 5555
      name: http-server
      targetPort: 5555
      nodePort: 30301
  type: NodePort
  sessionAffinity: ClientIP