apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tradingnetworks
spec:
  selector:
    matchLabels:
      app: tradingnetworks
      version: v1.0
      component: msr
  replicas: 1
  template:
    metadata:
      labels:
        app: tradingnetworks
        component: msr
        version: v1.0
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "tradingnetworks"        
      containers:      
        - name: tradingnetworks-container       
          image: wm.msr.tn.app:<TAG>
          imagePullPolicy: IfNotPresent   
        # Resources required for the apigateway to function. CPUs and Memory configurations.
          resources:
            limits:
              cpu: "1"
              memory: "2G" 
            requests:
              cpu: "0.25"
              memory: "1G"  
          env:
          - name: JAVA_MIN_MEM
            value: "1024M"
          - name: JAVA_MAX_MEM
            value: "2048M"     
          ports:
            - containerPort: 5555
        # Liveness probe to check whether container is active. Restart happens when liveness probe fails.
          livenessProbe:
            tcpSocket:
              port: 5555
            timeoutSeconds: 5
            initialDelaySeconds: 60
            failureThreshold: 5
            periodSeconds: 20
            successThreshold: 1
        # Readiness probe to check whether pod is ready to serve the requests. Traffic will not be injected unless readiness probes passes.
          readinessProbe:
            tcpSocket:
              port: 5555
            timeoutSeconds: 5
            initialDelaySeconds: 60
            failureThreshold: 5
            periodSeconds: 20
            successThreshold: 1            
        # Volume mount for Terracotta/Integration Server license key.
          volumeMounts:
            - mountPath: /opt/softwareag/IntegrationServer/bin/../config/licenseKey.xml
              subPath: licenseKey.xml
              name: licensekey
            - mountPath: /opt/softwareag/common/conf/terracotta-license.key
              subPath: terracotta-license.key
              name: licensekey
            - name: application-properties
              mountPath: /opt/softwareag/IntegrationServer/application.properties
              subPath: application.properties  
            - name: setenv-cp  
              mountPath: /opt/softwareag/IntegrationServer/packages/WmTN/bin/setcp.sh
              subPath: setcp.sh        
            - name: setenv   
              mountPath: /opt/softwareag/install/bin/setenv.sh
              subPath: setenv.sh                                    
      imagePullSecrets:
        - name: regcred
        - name: sagregcred                
      volumes:
        - name: licensekey
          configMap:
            name: webmethodslicensekeys
        - name: application-properties
          configMap:
            name: tn-appprop-cm
        - name: setenv-cp
          configMap:
            name: tn-utilfiles-cm
            defaultMode: 0777     
        - name: setenv
          configMap:
            name: tn-utilfiles-cm
            defaultMode: 0777              